[functions.create-checkout]
verify_jwt = true

[functions.flutterwave-webhook]
verify_jwt = false

[functions.check-result]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.issue-pins]
verify_jwt = true

[functions.student-register]
verify_jwt = false

[functions.create-student-invite]
verify_jwt = true